abilitiesData:
    abilities:
        convergence:
            # Highest level to which the ability can be upgraded
            maxLevel: 1
            # Relic level at which the ability becomes unlocked
            requiredLevel: 0
            # Number of leveling points needed to increase the ability level
            requiredPoints: 1
            stats: {
                }
levelingData:
    # Amount of experience required to level up to relic level 1
    initialCost: 1
    # Maximum level of the relic
    maxLevel: 1
    # Increment in experience required for each subsequent level of the relic
    step: 1
lootData:
    # List of key-value pairs where the key is a textual identifier for the loot table (supporting regular expressions) and the value represents the probability of generating the relic within the specified bounds
    entries: {
        }
