abilitiesData:
    abilities:
        restoration:
            # Highest level to which the ability can be upgraded
            maxLevel: 10
            # Relic level at which the ability becomes unlocked
            requiredLevel: 0
            # Number of leveling points needed to increase the ability level
            requiredPoints: 1
            stats: {
                }
levelingData:
    # Amount of experience required to level up to relic level 1
    initialCost: 100
    # Maximum level of the relic
    maxLevel: 1
    # Increment in experience required for each subsequent level of the relic
    step: 20
lootData:
    # List of key-value pairs where the key is a textual identifier for the loot table (supporting regular expressions) and the value represents the probability of generating the relic within the specified bounds
    entries:
        '[\w]+:chests\/[\w_\/]*(mineshaft|city|stronghold)[\w_\/]*': 0.025
        '[\w]+:chests\/[\w_\/]*(pillag|outpost)[\w_\/]*': 0.025
        minecraft:chests/woodland_mansion: 0.025
