abilitiesData:
    abilities:
        inoculation:
            # Highest level to which the ability can be upgraded
            maxLevel: 0
            # Relic level at which the ability becomes unlocked
            requiredLevel: 0
            # Number of leveling points needed to increase the ability level
            requiredPoints: 1
            stats: {
                }
        fortification:
            # Highest level to which the ability can be upgraded
            maxLevel: 5
            # Relic level at which the ability becomes unlocked
            requiredLevel: 3
            # Number of leveling points needed to increase the ability level
            requiredPoints: 1
            stats:
                reduction:
                    # Maximum base value of the stat. A random value within this range is assigned when the relic is first created
                    maxInitialValue: 20.0
                    # Maximum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    maxThresholdValue: 1.7976931348623157E308
                    # Minimum base value of the stat. A random value within this range is assigned when the relic is first created
                    minInitialValue: 12.0
                    # Minimum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    minThresholdValue: 4.9E-324
                    # Modifier applied to the base value of the stat, depending on the [upgradeOperation] parameter.
                    upgradeModifier: 4.0
                    # Type of mathematical operation used to calculate the stat's value based on the ability level. Supported operations include:
                    # MULTIPLY_BASE: x + ((x * y) * z),
                    # MULTIPLY_TOTAL: x * (y + 1)^z,
                    # ADD: x + (y * z).
                    # 
                    # ...where x - Base stat value, y - Value of [upgradeModifier], z - Current relic level
                    upgradeOperation: ADD
                increase:
                    # Maximum base value of the stat. A random value within this range is assigned when the relic is first created
                    maxInitialValue: 35.0
                    # Maximum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    maxThresholdValue: 1.7976931348623157E308
                    # Minimum base value of the stat. A random value within this range is assigned when the relic is first created
                    minInitialValue: 25.0
                    # Minimum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    minThresholdValue: 4.9E-324
                    # Modifier applied to the base value of the stat, depending on the [upgradeOperation] parameter.
                    upgradeModifier: 5.0
                    # Type of mathematical operation used to calculate the stat's value based on the ability level. Supported operations include:
                    # MULTIPLY_BASE: x + ((x * y) * z),
                    # MULTIPLY_TOTAL: x * (y + 1)^z,
                    # ADD: x + (y * z).
                    # 
                    # ...where x - Base stat value, y - Value of [upgradeModifier], z - Current relic level
                    upgradeOperation: ADD
        acquired_immunity:
            # Highest level to which the ability can be upgraded
            maxLevel: 0
            # Relic level at which the ability becomes unlocked
            requiredLevel: 5
            # Number of leveling points needed to increase the ability level
            requiredPoints: 1
            stats: {
                }
        cyberpsychosis:
            # Highest level to which the ability can be upgraded
            maxLevel: 3
            # Relic level at which the ability becomes unlocked
            requiredLevel: 5
            # Number of leveling points needed to increase the ability level
            requiredPoints: 1
            stats:
                duration:
                    # Maximum base value of the stat. A random value within this range is assigned when the relic is first created
                    maxInitialValue: 7.0
                    # Maximum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    maxThresholdValue: 1.7976931348623157E308
                    # Minimum base value of the stat. A random value within this range is assigned when the relic is first created
                    minInitialValue: 4.0
                    # Minimum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    minThresholdValue: 4.9E-324
                    # Modifier applied to the base value of the stat, depending on the [upgradeOperation] parameter.
                    upgradeModifier: 2.0
                    # Type of mathematical operation used to calculate the stat's value based on the ability level. Supported operations include:
                    # MULTIPLY_BASE: x + ((x * y) * z),
                    # MULTIPLY_TOTAL: x * (y + 1)^z,
                    # ADD: x + (y * z).
                    # 
                    # ...where x - Base stat value, y - Value of [upgradeModifier], z - Current relic level
                    upgradeOperation: ADD
                chance:
                    # Maximum base value of the stat. A random value within this range is assigned when the relic is first created
                    maxInitialValue: 5.0
                    # Maximum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    maxThresholdValue: 1.7976931348623157E308
                    # Minimum base value of the stat. A random value within this range is assigned when the relic is first created
                    minInitialValue: 3.0
                    # Minimum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    minThresholdValue: 4.9E-324
                    # Modifier applied to the base value of the stat, depending on the [upgradeOperation] parameter.
                    upgradeModifier: 1.0
                    # Type of mathematical operation used to calculate the stat's value based on the ability level. Supported operations include:
                    # MULTIPLY_BASE: x + ((x * y) * z),
                    # MULTIPLY_TOTAL: x * (y + 1)^z,
                    # ADD: x + (y * z).
                    # 
                    # ...where x - Base stat value, y - Value of [upgradeModifier], z - Current relic level
                    upgradeOperation: ADD
levelingData:
    # Amount of experience required to level up to relic level 1
    initialCost: 120
    # Maximum level of the relic
    maxLevel: 8
    # Increment in experience required for each subsequent level of the relic
    step: 30
lootData:
    # List of key-value pairs where the key is a textual identifier for the loot table (supporting regular expressions) and the value represents the probability of generating the relic within the specified bounds
    entries:
        minecraft:chests/ancient_city: 0.025
        minecraft:chests/ancient_city_ice_box: 0.025
        '[\w]+:chests\/[\w_\/]*(warden|sculk|echo)[\w_\/]*': 0.025
        '[\w]+:chests\/[\w_\/]*(end|warp)[\w_\/]*': 0.025
