abilitiesData:
    abilities:
        weaver:
            # Highest level to which the ability can be upgraded
            maxLevel: 3
            # Relic level at which the ability becomes unlocked
            requiredLevel: 0
            # Number of leveling points needed to increase the ability level
            requiredPoints: 1
            stats:
                passive_regen_time:
                    # Maximum base value of the stat. A random value within this range is assigned when the relic is first created
                    maxInitialValue: 5.0
                    # Maximum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    maxThresholdValue: 1.7976931348623157E308
                    # Minimum base value of the stat. A random value within this range is assigned when the relic is first created
                    minInitialValue: 7.0
                    # Minimum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    minThresholdValue: 4.9E-324
                    # Modifier applied to the base value of the stat, depending on the [upgradeOperation] parameter.
                    upgradeModifier: -0.5
                    # Type of mathematical operation used to calculate the stat's value based on the ability level. Supported operations include:
                    # MULTIPLY_BASE: x + ((x * y) * z),
                    # MULTIPLY_TOTAL: x * (y + 1)^z,
                    # ADD: x + (y * z).
                    # 
                    # ...where x - Base stat value, y - Value of [upgradeModifier], z - Current relic level
                    upgradeOperation: ADD
        bind:
            # Highest level to which the ability can be upgraded
            maxLevel: 3
            # Relic level at which the ability becomes unlocked
            requiredLevel: 0
            # Number of leveling points needed to increase the ability level
            requiredPoints: 1
            stats:
                healing_amount:
                    # Maximum base value of the stat. A random value within this range is assigned when the relic is first created
                    maxInitialValue: 4.0
                    # Maximum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    maxThresholdValue: 1.7976931348623157E308
                    # Minimum base value of the stat. A random value within this range is assigned when the relic is first created
                    minInitialValue: 2.0
                    # Minimum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    minThresholdValue: 4.9E-324
                    # Modifier applied to the base value of the stat, depending on the [upgradeOperation] parameter.
                    upgradeModifier: 0.5
                    # Type of mathematical operation used to calculate the stat's value based on the ability level. Supported operations include:
                    # MULTIPLY_BASE: x + ((x * y) * z),
                    # MULTIPLY_TOTAL: x * (y + 1)^z,
                    # ADD: x + (y * z).
                    # 
                    # ...where x - Base stat value, y - Value of [upgradeModifier], z - Current relic level
                    upgradeOperation: ADD
        soar:
            # Highest level to which the ability can be upgraded
            maxLevel: 3
            # Relic level at which the ability becomes unlocked
            requiredLevel: 3
            # Number of leveling points needed to increase the ability level
            requiredPoints: 1
            stats:
                speed_duration:
                    # Maximum base value of the stat. A random value within this range is assigned when the relic is first created
                    maxInitialValue: 10.0
                    # Maximum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    maxThresholdValue: 1.7976931348623157E308
                    # Minimum base value of the stat. A random value within this range is assigned when the relic is first created
                    minInitialValue: 7.0
                    # Minimum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    minThresholdValue: 4.9E-324
                    # Modifier applied to the base value of the stat, depending on the [upgradeOperation] parameter.
                    upgradeModifier: 2.0
                    # Type of mathematical operation used to calculate the stat's value based on the ability level. Supported operations include:
                    # MULTIPLY_BASE: x + ((x * y) * z),
                    # MULTIPLY_TOTAL: x * (y + 1)^z,
                    # ADD: x + (y * z).
                    # 
                    # ...where x - Base stat value, y - Value of [upgradeModifier], z - Current relic level
                    upgradeOperation: ADD
                leap_power:
                    # Maximum base value of the stat. A random value within this range is assigned when the relic is first created
                    maxInitialValue: 1.2999999523162842
                    # Maximum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    maxThresholdValue: 1.7976931348623157E308
                    # Minimum base value of the stat. A random value within this range is assigned when the relic is first created
                    minInitialValue: 1.100000023841858
                    # Minimum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    minThresholdValue: 4.9E-324
                    # Modifier applied to the base value of the stat, depending on the [upgradeOperation] parameter.
                    upgradeModifier: 0.10000000149011612
                    # Type of mathematical operation used to calculate the stat's value based on the ability level. Supported operations include:
                    # MULTIPLY_BASE: x + ((x * y) * z),
                    # MULTIPLY_TOTAL: x * (y + 1)^z,
                    # ADD: x + (y * z).
                    # 
                    # ...where x - Base stat value, y - Value of [upgradeModifier], z - Current relic level
                    upgradeOperation: ADD
        unravel:
            # Highest level to which the ability can be upgraded
            maxLevel: 3
            # Relic level at which the ability becomes unlocked
            requiredLevel: 6
            # Number of leveling points needed to increase the ability level
            requiredPoints: 1
            stats:
                damage:
                    # Maximum base value of the stat. A random value within this range is assigned when the relic is first created
                    maxInitialValue: 6.0
                    # Maximum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    maxThresholdValue: 1.7976931348623157E308
                    # Minimum base value of the stat. A random value within this range is assigned when the relic is first created
                    minInitialValue: 4.0
                    # Minimum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    minThresholdValue: 4.9E-324
                    # Modifier applied to the base value of the stat, depending on the [upgradeOperation] parameter.
                    upgradeModifier: 2.0
                    # Type of mathematical operation used to calculate the stat's value based on the ability level. Supported operations include:
                    # MULTIPLY_BASE: x + ((x * y) * z),
                    # MULTIPLY_TOTAL: x * (y + 1)^z,
                    # ADD: x + (y * z).
                    # 
                    # ...where x - Base stat value, y - Value of [upgradeModifier], z - Current relic level
                    upgradeOperation: ADD
                slow_duration:
                    # Maximum base value of the stat. A random value within this range is assigned when the relic is first created
                    maxInitialValue: 3.0
                    # Maximum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    maxThresholdValue: 1.7976931348623157E308
                    # Minimum base value of the stat. A random value within this range is assigned when the relic is first created
                    minInitialValue: 2.0
                    # Minimum threshold value for the stat, representing hard limits that cannot be surpassed through ability level upgrades or other methods
                    minThresholdValue: 4.9E-324
                    # Modifier applied to the base value of the stat, depending on the [upgradeOperation] parameter.
                    upgradeModifier: 0.5
                    # Type of mathematical operation used to calculate the stat's value based on the ability level. Supported operations include:
                    # MULTIPLY_BASE: x + ((x * y) * z),
                    # MULTIPLY_TOTAL: x * (y + 1)^z,
                    # ADD: x + (y * z).
                    # 
                    # ...where x - Base stat value, y - Value of [upgradeModifier], z - Current relic level
                    upgradeOperation: ADD
levelingData:
    # Amount of experience required to level up to relic level 1
    initialCost: 140
    # Maximum level of the relic
    maxLevel: 12
    # Increment in experience required for each subsequent level of the relic
    step: 40
lootData:
    # List of key-value pairs where the key is a textual identifier for the loot table (supporting regular expressions) and the value represents the probability of generating the relic within the specified bounds
    entries: {
        }
