
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.leaves_type]

		[types.leaves_type.autumnity]
			maple = true
			yellow_maple = true
			orange_maple = true
			red_maple = true

		[types.leaves_type.vinery]
			grapevine = true
			dark_cherry = true
			apple = true

		[types.leaves_type.beachparty]
			palm = true

		[types.leaves_type.meadow]
			pine = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.windswept]
			holly = true
			chestnut = true
			pine = true
			flowering_acacia = true

		[types.leaves_type.cluttered]
			willow = true
			flowering_willow = false
			poplar = true
			flowering_poplar = false
			crabapple = false
			flowering_crabapple = false
			sycamore = true
			fluorescent_maple = false
			flowering_fluorescent_maple = true

		[types.leaves_type.vanillabackport]
			pale_oak = true

		[types.leaves_type.twilightdelight]
			ironwood = true

		[types.leaves_type.aether]
			skyroot = true
			golden_oak = true
			crystal = true
			crystal_fruit = true
			holiday = true
			decorated_holiday = true

		[types.leaves_type.twilightforest]
			thorn = true
			beanstalk = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

	[types.wood_type]

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.vinery]
			dark_cherry = true

		[types.wood_type.beachparty]
			palm = true

		[types.wood_type.meadow]
			pine = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

		[types.wood_type.betterarcheology]
			rotten = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.windswept]
			holly = true
			chestnut = true
			pine = true

		[types.wood_type.cluttered]
			willow = true
			flowering_willow = false
			poplar = true
			flowering_poplar = false
			crabapple = false
			flowering_crabapple = false
			sycamore = true
			fluorescent_maple = false
			blue_mushroom = false
			red_mushroom = false

		[types.wood_type.vanillabackport]
			pale_oak = true

		[types.wood_type.domum_ornamentum]
			cactus = true
			cactus_extra = true

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

	[types.cake]

		[types.cake.veggiesdelight]
			carrot_cake = true

#Disables specific entries
[entries]

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = false
			leaf_carpet = true

		[entries.leaves_type.refurbished_furniture]
			hedge = true

	[entries.wood_type]

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			trapped_chest = false
			bookshelf = true
			chest = false
			stripped_post = true
			ladder = true
			hollow_log = true
			vertical_slab = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.create]
			window = false
			window_pane = false

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.refurbished_furniture]
			cutting_board = false
			drawer = true
			storage_cabinet = true
			table = true
			mail_box = true
			dark_ceiling_fan = false
			kitchen_sink = true
			toilet = false
			storage_jar = false
			lattice_fence = true
			basin = false
			kitchen_drawer = true
			lattice_fence_gate = true
			kitchen_cabinetry = true
			bath = false
			crate = true
			desk = true
			chair = true
			light_ceiling_fan = false
			kitchen_storage_cabinet = true

		[entries.wood_type.functionalstorage]
			1 = true
			4 = true
			2 = true

		[entries.wood_type.twigs]
			table = false

		[entries.wood_type.beautify]
			trellis = true
			blinds = true
			picture_frame = false

		[entries.wood_type.dramaticdoors]
			short_door = true
			tall_door = true

		[entries.wood_type.twilightforest]
			banister = true
			hollow_log_climbable = true
			hollow_log_horizontal = true
			hollow_log_vertical = true

